[TICKET-87] Festival, FestivalDetail Refactoring & Featuring
java-book-study/TICKET-EXPEDITIONARY-FORCE pull request #51
Opened 2020-11-30 19:08 UTC by Be-poz

# [TICKET-87] Festival, FestivalDetail Refactoring & Featuring
<br>

### 완료 조건

- [x] `Festival 엔티티 및 관련 Dto 수정`
- [x] `FestivalDetail 엔티티 및 관련 Dto 수정`
- [x] `Festival test 코드 작성`
- [x] `FestivalDetail test 코드 작성`
- [x] `Controller 가 가지는 문제들을 해결`

<br> 

### 주안점

1. Festiva, FestivalDetail 엔티티와 관련 Dto들 다 수정했습니다.
필드값 수정에 대한 설명은 생략하겠습니다. Dto들 내부의 toDto 메서드를 모두 삭제했습니다. 해당 메서드들은 사용되지 않기에 삭제했습니다. Controller에서 바로 dto 로 받아오고 그 dto 를 service 단에 넘기기 때문에 불필요한 메서드라고 판단했습니다.  
builder패턴들은 유지해두었습니다. 삭제해도 무방하긴 하지만 test코드 작성에 들어가서 냅뒀습니다.  

FestivalCreateDto 에서 Festival_Detail에 대한 내용은 갖고 있지 않습니다. 해당 값 삽입은 Festival 내부 메서드를 이용할 예정입니다. 반면, FestivalDetailCreateDto에서는 Festival를 받아옵니다. 한 개의 값을 가지기 때문이기도 하고 로직 상 '다' 쪽을 먼저 만들기 때문에 dto 내부에서 넣어줘도 된다고 파악했습니다. 더 내용이 있었던 것 같은데 수정작업이 너무 많았어서 잘 기억이 안나네요...  

2. 테스트 코드들을 작성했습니다.  
FestivalDetail 에 대한 테스트 코드들은 아예 존재하지 않아서 제가 추가하였습니다.  
Festival에 대한 테스트 코드들도 재수정 하였습니다. generate과 update 에 대한 메서드가 존재 하지 않아서 추가했습니다. 이 과정에서 기존의 ``@Before`` 를 이용한 save 과정을 없애고 generate으로 처리하였습니다. 진행 과정에서 generate 과 update API 가 문제가 있어 에러가 뜨는 것을 발견해서 controller 수정해주었습니다. 이 이유 때문에 기존 테스트에서 빼셨던 것 같습니다. Dto 값을 제대로 못받아오는 것이 문제였는데 ``@RequestBody``가 생략되었던거였습니다.  
Validator 로직이 `!=` 여야 하는데 `==` 길레 수정했습니다. 해당 validator 검증 테스트가 없길레 추가했습니다. 이 과정에서 initBinder 메서드를 사용하게 되는데 update 테스트가 해당 validator 를 추가하면 깨지는 것을 발견했고 계속 봤으나 해결하지 못했습니다. @Valid 를 걸어주지 않았는데 걸리고 그 문제인 것 같습니다. 내일 해결 예정입니다. 그리고 validator 테스트 시에 해당 발생 error 를 리턴하고 싶은데 ApiResponseDto<FestivalCreateDto> 로 고정이 되어있어서 원하는대로 error 를 리턴 못하고 exception 을 던지게 됩니다. 이 부분 어떻게 해결해야할지 의논하고 싶습니다. 테스트 코드에서는 try catch 로 exception 처리해준 상태입니다. 내일 따로 exception 만들고 exceptionhandler 로 처리할 예정입니다.  

createDto, updateDto, 일반dto 가 현재 있고 api의 리턴을 일반dto로 모두 담당하고 있습니다. 하지만, api 별 스펙에 맞춘 dto를 리턴하는게 맞습니다. 현재 FestivalDetailDto를 보면 Festival festival 필드가 있고 @JsonIgnore 되어 있습니다. 왜냐하면 findById 로 FestivalDetail를 가지고 오고 이를 dto로 변환할 때에 serializer 관한 에러가 납니다. lazy 로딩으로 인한 문제입니다. FestivalDto 내부에 아직 FestivalDetail에 관한 필드를 추가하지 않았는데 마찬가지로 오류가 나게 될 것이고 이를 해결하려면 따로 변환을 해주어야 합니다. 이쪽 내용이 정확히 생각이 안나고 개념이 좀 흐릿해진 것 같아서 다시 공부하고 차후에 변경하도록 하겠습니다.  

내일은 date 처리, update테스트의 validator 문제 해결 그리고 dto 변환에 관한 것을 찾아볼 예정입니다. 변경 내용이 많아서 file changed를 다 확인하시기 매우 힘드실 것 같습니다. 만약 시간이 없으시다면 승인만이라도 눌러주시면 감사하겠습니다...

<br>

## 체크리스트

- [x] PR 제목은 유의미한가요?
- [x] 무엇을 변경했는지 충분히 설명하고 있나요?
- [ ] reference가 있다면 추가했나요?
- [x] 작업을 설명하는 Jira 티켓을 추가했나요?
- [x] 작업 범위에 대해서 테스트를 작성하셨나요?
- [x] 팀원 두명을 Assign하고, Review Request에는 모든 팀원을 추가했나요?
- [ ] 새로운 기술을 사용했다면, 그 기술을 설명하고 있나요?
- [x] 이해하기 어려운 비즈니스 로직에 관해서 부연 설명을 하고 있나요?
- [ ] 인프라 작업, 릴리즈 PR이라면, Review Skip 레이블을 추가했나요?

---

2020-12-01 06:22 UTC, dmstjd1024 requested changes
리뷰 올렸습니다~

2020-12-01 06:22 UTC, dmstjd1024 commented on src/main/java/com/ticket/captain/festival/dto/FestivalCreateDto.java
> +                             LocalDateTime salesStartDate, LocalDateTime salesEndDate, String festivalCategory) {
@CreationTimestamp 어노테이션을 사용한다면 LocalDateTime에서 salesStartDate 를 넣어줄 필요가 없을거 같아요~

2020-12-01 06:22 UTC, dmstjd1024 commented on src/main/java/com/ticket/captain/festival/FestivalManagerController.java
> +@RequestMapping(value = "/api/manager/festival", produces = MediaTypes.HAL_JSON_VALUE)
hateoas를 적용해야 hal json으로 리턴됩니다~

2020-12-01 06:22 UTC, dmstjd1024 commented on src/main/java/com/ticket/captain/festival/dto/FestivalCreateDto.java
> -    @NotBlank
valid 지우신 이유가 무엇인가요?

2020-12-01 06:22 UTC, dmstjd1024 commented on src/main/resources/application.yml
>  spring:
application.yml 올리실 때 수정해서 올리지 말아주세요..

2020-12-01 06:22 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festival/FestivalControllerTest.java
> +    @Order(1)
tdd 스럽게 만드실거면 @order 안쓰는게 좋다 생각합니다! @order로 테스트에 순서를 정해주면 한 테스트가 다른 테스트에 영향을 줄 수 도 있기 때문이에요~

2020-12-01 06:22 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festival/FestivalControllerTest.java
> +            mockMvc.perform(post(API_MANAGER_URL + "/generate/")
이 부분 같은 경우 valid에 대한 처리가 없기 때문에 Exception 그대로를 던져주어서 테스트가 에러가 납니다 한번 확인 부탁드려요~

2020-12-01 06:22 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festival/FestivalControllerTest.java
> +    void updateFestival() throws Exception {
이 부분에서 위에 FestivalCreateValidator bean으로 생성한 객체를 안쓰고 새로 FestivalCreateValidator validator = new FestivalCreateValidator(festivalService); 라고 코드를 쓰셔서 그런가 FestivalUpdateDto에 대한 Invalid target for Validator 에러가 납니다!

2020-12-01 06:22 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festival/FestivalUserControllerTest.java
>          FestivalDto festivalDto = festivalService.add(createDto);
이부분에서 add 전에 festivalService.findAll(Pageable.unpaged()); 디버깅 해봤는데 벌써 안에 똑같은 객체가 있어서 query did not return a unique result: 2 나오네요 확인 부탁드려요~

2020-12-01 06:22 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festivalDetail/FestivalDetailRestControllerTest.java
> +    public void infoTest() throws Exception{
빈 db에서 실행하면 NotFoundException 일어납니다ㅠ

2020-12-01 06:22 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festivalDetail/FestivalDetailRestControllerTest.java
> +    public void updateTest() throws Exception{
빈 db에서 실행하면 NotFoundException 일어납니다ㅠ

2020-12-01 06:22 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festivalDetail/FestivalDetailRestControllerTest.java
> +    public void deleteTest() throws Exception{
빈 db에서 실행하면 NotFoundException 일어납니다ㅠ

2020-12-01 11:50 UTC, Be-poz commented on src/main/java/com/ticket/captain/festival/dto/FestivalCreateDto.java
> +                             LocalDateTime salesStartDate, LocalDateTime salesEndDate, String festivalCategory) {
time 부분은 지금 따로 작업합니다! salesStartDate은 createDate이랑 별개로 둘 것 같아요

2020-12-01 11:51 UTC, Be-poz commented on src/main/java/com/ticket/captain/festival/dto/FestivalCreateDto.java
> -    @NotBlank
일단 모든 valid 다 지웠습니다. db보고 다시 재설정해야 되는 부분들이 많아서요

2020-12-01 11:51 UTC, Be-poz commented on src/main/resources/application.yml
>  spring:
이거 까먹었습니다 ㅜㅜ

2020-12-01 11:52 UTC, Be-poz commented on src/test/java/com/ticket/captain/festival/FestivalControllerTest.java
> +    @Order(1)
기존의 FestivalControllerTest 에서 수정위주로 해서 남았고 Detail은 이 방식 따라서 Order 사용했는데 하면안되겠네요

2020-12-01 11:53 UTC, Be-poz commented on src/test/java/com/ticket/captain/festival/FestivalControllerTest.java
> +            mockMvc.perform(post(API_MANAGER_URL + "/generate/")
슬랙에 답변드렸습니다. 의도한대로 처리된거 맞습니당

2020-12-01 11:56 UTC, Be-poz commented on src/test/java/com/ticket/captain/festivalDetail/FestivalDetailRestControllerTest.java
> +    public void infoTest() throws Exception{
order 있기 떄문에 전체 실행을 의도해서 만든 테스트입니다.

2020-12-01 11:56 UTC, Be-poz commented on src/test/java/com/ticket/captain/festivalDetail/FestivalDetailRestControllerTest.java
> +    public void updateTest() throws Exception{
상동

2020-12-01 11:56 UTC, Be-poz commented on src/test/java/com/ticket/captain/festivalDetail/FestivalDetailRestControllerTest.java
> +    public void deleteTest() throws Exception{
상동

2020-12-01 11:59 UTC, Be-poz commented on src/test/java/com/ticket/captain/festival/FestivalUserControllerTest.java
>          FestivalDto festivalDto = festivalService.add(createDto);
저는 통과 잘되는데 ddl-auto  설정 혹시 none 으로 되어있는거 아닌가요 ?

2020-12-01 12:07 UTC, Be-poz commented on src/test/java/com/ticket/captain/festival/FestivalControllerTest.java
> +    void updateFestival() throws Exception {
이 부분 이유 모르겠던 부분인데, 해당 지적 부분은 제가 필드에다가 두는 방식이랑 initBinder로 두는 방식 둘 다 진행하다가 필드에 둔 것을 삭제못한 것 같네요. 해당 필드에 주입한 것을 삭제해도 동일한 오류가 뜹니다. 아직 해결방안을 찾지 못했습니다.

2020-12-01 12:09 UTC, Be-poz commented on src/test/java/com/ticket/captain/festivalDetail/FestivalDetailRestControllerTest.java
> +    public void infoTest() throws Exception{
validatorTest 가 들어가면서 연속으로 실행하기가 애매해 진 것 같네요

2020-12-01 12:41 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festival/FestivalUserControllerTest.java
>          FestivalDto festivalDto = festivalService.add(createDto);
h2 메모리 db에 create로 동작 시켰습니다~ 한번 바꿔서 확인 부탁드려요~

2020-12-01 12:45 UTC, dmstjd1024 commented on src/test/java/com/ticket/captain/festivalDetail/FestivalDetailRestControllerTest.java
> +    public void infoTest() throws Exception{
이부분도 테스트 돌릴 때 Order에 의존하는건 좋지 않다 생각합니다~

2020-12-02 02:49 UTC, dmstjd1024 approved these changes
커밋이랑 file changed가 너무 많아서 상세히 보지는 못했지만 승윤님 믿고 approve 하겠습니다!

2020-12-02 11:39 UTC, HyunSung-Na approved these changes
고생하셨습니다! 엄청나게 작업하셨내요! 일단 다 보긴했는데 수정사항이 많아서 천천히 보면서 궁금한 내용이 있으면 물어보겠습니다!

2020-12-02 16:20 UTC, 9m1i9n1 approved these changes

2020-12-02 17:07 UTC, merged